### ISSUE TITLE
Update gatsby template

### ISSUE THREAD

**Issue by xlc** [open-rpc/generator#721]
It is 4 years old with many warnings and built error on macos

```
  ⚙️  gatsby [5/6] info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.10.5/libvips-8.10.5-darwin-arm64v8.tar.br
ERR! sharp Prebuilt libvips 8.10.5 binaries are not yet available for darwin-arm64v8
info sharp Attempting to build from source via node-gyp but this may fail due to the above error
info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.1
gyp info using node@23.3.0 | darwin | arm64
(node:40876) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info find Python using Python version 3.13.0 found at "/opt/homebrew/opt/python@3.13/bin/python3.13"
(node:40876) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
gyp ERR! stack     at createConfigFile (/Users/xiliangchen/projects/jam-rpc-spec/build/docs/gatsby/node_modules/node-gyp/lib/configure.js:118:21)
gyp ERR! stack     at /Users/xiliangchen/projects/jam-rpc-spec/build/docs/gatsby/node_modules/node-gyp/lib/configure.js:85:9
gyp ERR! stack     at /Users/xiliangchen/projects/jam-rpc-spec/build/docs/gatsby/node_modules/mkdirp/index.js:30:20
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:188:23)
gyp ERR! System Darwin 24.1.0
gyp ERR! command "/opt/homebrew/Cellar/node/23.3.0/bin/node" "/Users/xiliangchen/projects/jam-rpc-spec/build/docs/gatsby/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/xiliangchen/projects/jam-rpc-spec/build/docs/gatsby/node_modules/sharp
gyp ERR! node -v v23.3.0
gyp ERR! node-gyp -v v5.1.1
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
```

**Comment by xlc** [comment]
Maybe it is abandoned and should just use the playground instead?

**Comment by shanejonas** [comment]
should be fixed in the latest major version bump https://github.com/open-rpc/generator/pull/723. let us know if you are still having any issues.
